### ISSUE TITLE
Internal error found in jax-triton for fused attention

### ISSUE THREAD

**Issue by wukefe** [jax-ml/jax-triton#93] opened 2023-02-28 01:19 UTC
## Overview

We wrote a program in jax-triton derived from Triton's example for fused attention (06-fused-attention.py).  In terms of the triton kernel in the program, it contains only minimal change.  See the script `main.py` [1] and the environment `env.txt` [2] for details.

## How to run

A simple run as follows can replicate the errors included in `error.log` [3]
```
python main.py
```

jax-triton fails at some input shapes
```
qkv: (2, 2, 32, 32)  # pass
qkv: (2, 2, 128, 64)  # pass
qkv: (2, 2, 256, 64)  # failed
```

It seems an internal error:
```
...
  File "/home/xx/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 468, in triton_call
    out_flat = triton_kernel_call_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: IndexError: map::at
```

1. [main.py](https://github.com/jax-ml/jax-triton/files/10845627/main.py.txt)
1. [env.txt](https://github.com/jax-ml/jax-triton/files/10845621/env.txt)
1. [error.txt](https://github.com/jax-ml/jax-triton/files/10845622/error.txt)

**Comment by sharadmv** [comment] 2023-02-28 02:01
I strongly suspect that this is Triton compiler bug. We could verify this by reproducing the same error using vanilla Triton (w/ the same kernel). If so, it is likely fixed w/ Triton MLIR (as opposed to the legacy version we are using w/ jax-triton). Then when we eventually migrate to MLIR, this should be fixed.

**Comment by sharadmv** [comment] 2023-02-28 02:02
Alternatively, could you try using `jax_triton.pallas.ops.mha`?

**Comment by wukefe** [comment] 2023-02-28 02:18
We have tested the triton code [main-triton.py](https://github.com/jax-ml/jax-triton/files/10845907/main-triton.py.txt) with triton 2.0.0.dev20221202.  All the above tests passed.  

```
python main-triton.py
```

When comparing jax-triton and triton kernels, we can see that they are almost identical.  In additional, the choices of settings have been limited to the same block sizes (128,128), num_stages (1), and num_warps (16).

Could you help check them to see if we miss anything?

**Comment by vinodgro** [comment] 2023-02-28 06:32
it fails for sequence lengths 256, 384, 512 and 1024

**Comment by sharadmv** [comment] 2023-03-02 00:05
I'm still investigating, but I think it has to do w/ causal vs non-causal attention.  I have a fixed version here: https://github.com/jax-ml/jax-triton/compare/fix-attn?expand=1. Could you try that out?

**Comment by wukefe** [comment] 2023-03-02 00:39
Sure, I just tried the branch (`fix-attn`) in #95 and saw a new error (saved in [error-fix-attn.txt](https://github.com/jax-ml/jax-triton/files/10866520/error-fix-attn.txt)).
```
>> python main.py
...
AttributeError: module 'jax._src.state' has no attribute 'AbstractRef'
```

Installed jax-triton version with commit: 7b6761870fe14ce31004ca7517d30f6224414a31

**Comment by sharadmv** [comment] 2023-03-02 02:00
Sorry you'll need to use JAX at HEAD

**Comment by wukefe** [comment] 2023-03-10 21:44
Sorry for the late reply!  I actually tried a couple of combinations for jax and jax-triton.

1. jax (0.4.6) + jax-triton (branch: fix-attn)
2. jax (0.4.6) + jax-triton (HEAD: 0678c96d9f6d0815cf45f688091528f15b304eb1)

The newer version 0.4.6 (released yesterday, previously 0.4.4) fixed the issue about the attribute not found.  However, the IndexError still persists.  (Please see the complete log attached [error-with-jax-0.4.6.txt](https://github.com/jax-ml/jax-triton/files/10946322/error-with-jax-0.4.6.txt))

```
>> python main.py
...
jax._src.source_info_util.JaxStackTraceBeforeTransformation: IndexError: map::at
```

**Comment by sharadmv** [comment] 2023-03-11 00:48
I can take a look soon. BTW we're really close to merging the MLIR branch. It might be worth trying things there (https://github.com/jax-ml/jax-triton/pull/50)

**Comment by sharadmv** [comment] 2023-05-24 18:31
I'll close this for now since we have rebased on MLIR. Feel free to re-open if you still run into issues

**Closed by sharadmv** 2023-05-24 18:31 UTC
